version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            #- "80:80"
            - "443:443"
        # слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: Dd7015015

    phpmyadmin: 
        image: phpmyadmin/phpmyadmin 
        environment: 
            MYSQL_ROOT_PASSWORD: Dd7015015 
        ports:
            - "80:80"
        links: # for mysql container
            - "mysql:mysql"

